export const healthCareList = [
  {"id": 1, "name": "Lagos University Teaching Hospital", "location": "Lagos", "address": "Idi-Araba, Surulere, Lagos"},
  {"id": 2, "name": "University College Hospital", "location": "Ibadan", "address": "Queen Elizabeth II Road, Ibadan"},
  {"id": 3, "name": "National Hospital Abuja", "location": "Abuja", "address": "Plot 132 Central District (Phase II), P.M.B. 425, Garki, Abuja"},
  {"id": 4, "name": "Aminu Kano Teaching Hospital", "location": "Kano", "address": "Kano - Wudil Road, Kano"},
  {"id": 5, "name": "University of Nigeria Teaching Hospital", "location": "Enugu", "address": "Ituku-Ozalla, Enugu"},
  {"id": 6, "name": "Ahmadu Bello University Teaching Hospital", "location": "Zaria", "address": "Shika-Zaria Road, Shika, Zaria"},
  {"id": 7, "name": "Federal Medical Centre, Ebute Metta", "location": "Lagos", "address": "Lagos - Ibadan Expressway, Ebute Metta, Lagos"},
  {"id": 8, "name": "University of Benin Teaching Hospital", "location": "Benin", "address": "Benin - Lagos Road, Benin"},
  {"id": 9, "name": "University of Port Harcourt Teaching Hospital", "location": "Port Harcourt", "address": "Aluu Road, Port Harcourt"},
  {"id": 10, "name": "Federal Medical Centre, Asaba", "location": "Asaba", "address": "Federal Medical Centre Road, Asaba"},
  {"id": 11, "name": "Lagos State University Teaching Hospital", "location": "Lagos", "address": "1-5 Oba Akinjobi Way, Ikeja, Lagos"},
  {"id": 12, "name": "Federal Medical Centre, Umuahia", "location": "Umuahia", "address": "Azikiwe Road, Umuahia"},
  {"id": 13, "name": "University of Ilorin Teaching Hospital", "location": "Ilorin", "address": "University of Ilorin Campus, Oke Oyi, Ilorin"},
  {"id": 14, "name": "Federal Medical Centre, Abeokuta", "location": "Abeokuta", "address": "Idi-Aba Road, Abeokuta"},
  {"id": 15, "name": "Nnamdi Azikiwe University Teaching Hospital", "location": "Nnewi", "address": "Nnewi - Nnobi Road, Nnewi"},
  {"id": 16, "name": "Federal Medical Centre, Owerri", "location": "Owerri", "address": "Orlu Road, Owerri"},
  {"id": 17, "name": "Federal Medical Centre, Yola", "location": "Yola", "address": "Lamido Zubairu Way, Yola"},
  {"id": 18, "name": "Federal Medical Centre, Makurdi", "location": "Makurdi", "address": "Yandev - Gboko Road, Makurdi"},
  {"id": 19, "name": "Federal Medical Centre, Birnin Kudu", "location": "Birnin Kudu", "address": "Birnin Kudu - Jahun Road, Birnin Kudu"},
  {"id": 20, "name": "Lagos State University Teaching Hospital", "location": "Lagos", "address": "1-5 Oba Akinjobi Way, Ikeja, Lagos"},
  {"id": 21, "name": "Federal Medical Centre, Bida", "location": "Bida", "address": "Bida - Minna Road, Bida"},
  {"id": 22, "name": "Federal Medical Centre, Lokoja", "location": "Lokoja", "address": "Lokoja - Okene Road, Lokoja"},
  {"id": 23, "name": "Niger Delta University Teaching Hospital", "location": "Bayelsa", "address": "Okolobiri, Bayelsa"},
  {"id": 24, "name": "Federal Medical Centre, Jalingo", "location": "Jalingo", "address": "Barrack Road, Jalingo"},
  {"id": 25, "name": "Federal Medical Centre, Gombe", "location": "Gombe", "address": "Independence Way, Gombe"},
  {"id": 26, "name": "Federal Medical Centre, Gusau", "location": "Gusau", "address": "Sokoto Road, Gusau"},
  {"id": 27, "name": "Federal Medical Centre, Katsina", "location": "Katsina", "address": "Katsina - Daura Road, Katsina"},
  {"id": 28, "name": "Federal Medical Centre, Keffi", "location": "Keffi", "address": "Keffi - Abuja Road, Keffi"},
  {"id": 29, "name": "Federal Medical Centre, Lafia", "location": "Lafia", "address": "Lafia - Akwanga Road, Lafia"},
  {"id": 30, "name": "Federal Medical Centre, Lokoja", "location": "Lokoja", "address": "Lokoja - Okene Road, Lokoja"},
  {"id": 31, "name": "Federal Medical Centre, Owo", "location": "Owo", "address": "Hospital Road, Owo"},
  {"id": 32, "name": "Federal Medical Centre, Owerri", "location": "Owerri", "address": "Orlu Road, Owerri"},
  {"id": 33, "name": "Federal Medical Centre, Sokoto", "location": "Sokoto", "address": "Sultan Abubakar Road, Sokoto"},
  {"id": 34, "name": "Federal Medical Centre, Umuahia", "location": "Umuahia", "address": "Azikiwe Road, Umuahia"},
  {"id": 35, "name": "Federal Medical Centre, Yenagoa", "location": "Yenagoa", "address": "Yenagoa - Mbiama Road, Yenagoa"},
  {"id": 36, "name": "Federal Medical Centre, Abeokuta", "location": "Abeokuta", "address": "Idi-Aba Road, Abeokuta"},
  {"id": 37, "name": "Federal Medical Centre, Azare", "location": "Azare", "address": "Kano Road, Azare"},
  {"id": 38, "name": "Federal Medical Centre, Bida", "location": "Bida", "address": "Bida - Minna Road, Bida"},
  {"id": 39, "name": "Federal Medical Centre, Birnin Kudu", "location": "Birnin Kudu", "address": "Birnin Kudu - Jahun Road, Birnin Kudu"},
  {"id": 40, "name": "Federal Medical Centre, Damaturu", "location": "Damaturu", "address": "Potiskum Road, Damaturu"},
  {"id": 41, "name": "Federal Medical Centre, Ebute Metta", "location": "Lagos", "address": "Lagos - Ibadan Expressway, Ebute Metta, Lagos"},
  {"id": 42, "name": "Federal Medical Centre, Gombe", "location": "Gombe", "address": "Independence Way, Gombe"},
  {"id": 43, "name": "Federal Medical Centre, Gusau", "location": "Gusau", "address": "Sokoto Road, Gusau"},
  {"id": 44, "name": "Federal Medical Centre, Ido-Ekiti", "location": "Ido-Ekiti", "address": "Ilorin - Ado Ekiti Road, Ido-Ekiti"},
  {"id": 45, "name": "Federal Medical Centre, Jalingo", "location": "Jalingo", "address": "Barrack Road, Jalingo"},
  {"id": 46, "name": "Federal Medical Centre, Katsina", "location": "Katsina", "address": "Katsina - Daura Road, Katsina"},
  {"id": 47, "name": "Federal Medical Centre, Keffi", "location": "Keffi", "address": "Keffi - Abuja Road, Keffi"},
  {"id": 48, "name": "Federal Medical Centre, Lokoja", "location": "Lokoja", "address": "Lokoja - Okene Road, Lokoja"},
  {"id": 49, "name": "Federal Medical Centre, Owerri", "location": "Owerri", "address": "Orlu Road, Owerri"},
  {"id": 50, "name": "Federal Medical Centre, Sokoto", "location": "Sokoto", "address": "Sultan Abubakar Road, Sokoto"},
  {"id": 51, "name": "General Hospital, Minna", "location": "Minna", "address": "Western By-pass Road, Minna"},
  {"id": 52, "name": "General Hospital, Zaria", "location": "Zaria", "address": "Zaria - Kano Road, Zaria"},
  {"id": 53, "name": "Isolo General Hospital", "location": "Lagos", "address": "Isolo Road, Isolo, Lagos"},
  {"id": 54, "name": "Gbagada General Hospital", "location": "Lagos", "address": "Gbagada Expressway, Gbagada, Lagos"},
  {"id": 55, "name": "Ikorodu General Hospital", "location": "Lagos", "address": "Ikorodu Road, Ikorodu, Lagos"},
  {"id": 56, "name": "Gwagwalada Specialist Hospital", "location": "Abuja", "address": "Gwagwalada - Kuje Road, Gwagwalada, Abuja"},
  {"id": 57, "name": "National Orthopaedic Hospital, Enugu", "location": "Enugu", "address": "Enugu - Port Harcourt Expressway, Enugu"},
  {"id": 58, "name": "Federal Medical Centre, Abakaliki", "location": "Abakaliki", "address": "Presco Junction, Abakaliki"},
  {"id": 59, "name": "Adeoyo Maternity Hospital", "location": "Ibadan", "address": "Ring Road, Ibadan"},
  {"id": 60, "name": "Eko Hospital", "location": "Lagos", "address": "Adetokunbo Ademola Street, Victoria Island, Lagos"},
  {"id": 61, "name": "Reddington Hospital", "location": "Lagos", "address": "12 Idowu Martins Street, Victoria Island, Lagos"},
  {"id": 62, "name": "St. Nicholas Hospital", "location": "Lagos", "address": "57 Campbell Street, Lagos Island, Lagos"},
  {"id": 63, "name": "First Consultant Hospital", "location": "Lagos", "address": "5 Mobolaji Bank Anthony Way, Maryland, Lagos"},
  {"id": 64, "name": "Nizamiye Hospital", "location": "Abuja", "address": "Cadastral Zone B04, Abuja"},
  {"id": 65, "name": "Primus Hospital", "location": "Abuja", "address": "Karimu Kotun Close, Abuja"},
  {"id": 66, "name": "Zenith Medical and Kidney Centre", "location": "Abuja", "address": "Plot 1075, Abuja"},
  {"id": 67, "name": "St. Edwards Hospital", "location": "Lagos", "address": "55 Bourdillon Road, Ikoyi, Lagos"},
  {"id": 68, "name": "St. Gregory's Hospital", "location": "Lagos", "address": "10b Olorunlogbon Street, Anthony Village, Lagos"},
  {"id": 69, "name": "Holy Trinity Hospital", "location": "Lagos", "address": "142 Akowonjo Road, Egbeda, Lagos"},
  {"id": 70, "name": "Medicare Specialist Hospital", "location": "Lagos", "address": "14B Ladoke Akintola Street, Ikeja GRA, Lagos"},
  {"id": 71, "name": "South Shore Women's and Children's Hospital", "location": "Lagos", "address": "11 Olabanji Olajide Street, Lekki Phase 1, Lagos"},
  {"id": 72, "name": "Doren Specialist Hospital", "location": "Lagos", "address": "21 Emina Crescent, Off Toyin Street, Ikeja, Lagos"},
  {"id": 73, "name": "Lagoon Hospitals", "location": "Lagos", "address": "Plot 8, Block 79, Providence Street, Lekki Phase 1, Lagos"},
  {"id": 74, "name": "Eko Hospital", "location": "Lagos", "address": "Adetokunbo Ademola Street, Victoria Island, Lagos"},
  {"id": 75, "name": "Reddington Hospital", "location": "Lagos", "address": "12 Idowu Martins Street, Victoria Island, Lagos"},
  {"id": 76, "name": "St. Nicholas Hospital", "location": "Lagos", "address": "57 Campbell Street, Lagos Island, Lagos"},
  {"id": 77, "name": "First Consultant Hospital", "location": "Lagos", "address": "5 Mobolaji Bank Anthony Way, Maryland, Lagos"},
  {"id": 78, "name": "Nizamiye Hospital", "location": "Abuja", "address": "Cadastral Zone B04, Abuja"},
  {"id": 79, "name": "Primus Hospital", "location": "Abuja", "address": "Karimu Kotun Close, Abuja"},
  {"id": 80, "name": "Zenith Medical and Kidney Centre", "location": "Abuja", "address": "Plot 1075, Abuja"},
  {"id": 81, "name": "St. Edwards Hospital", "location": "Lagos", "address": "55 Bourdillon Road, Ikoyi, Lagos"},
  {"id": 82, "name": "St. Gregory's Hospital", "location": "Lagos", "address": "10b Olorunlogbon Street, Anthony Village, Lagos"},
  {"id": 83, "name": "Holy Trinity Hospital", "location": "Lagos", "address": "142 Akowonjo Road, Egbeda, Lagos"},
  {"id": 84, "name": "Medicare Specialist Hospital", "location": "Lagos", "address": "14B Ladoke Akintola Street, Ikeja GRA, Lagos"},
  {"id": 85, "name": "South Shore Women's and Children's Hospital", "location": "Lagos", "address": "11 Olabanji Olajide Street, Lekki Phase 1, Lagos"},
  {"id": 86, "name": "Doren Specialist Hospital", "location": "Lagos", "address": "21 Emina Crescent, Off Toyin Street, Ikeja, Lagos"},
  {"id": 87, "name": "Lagoon Hospitals", "location": "Lagos", "address": "Plot 8, Block 79, Providence Street, Lekki Phase 1, Lagos"},
  {"id": 88, "name": "Eko Hospital", "location": "Lagos", "address": "Adetokunbo Ademola Street, Victoria Island, Lagos"},
  {"id": 89, "name": "Reddington Hospital", "location": "Lagos", "address": "12 Idowu Martins Street, Victoria Island, Lagos"},
  {"id": 90, "name": "St. Nicholas Hospital", "location": "Lagos", "address": "57 Campbell Street, Lagos Island, Lagos"},
  {"id": 91, "name": "First Consultant Hospital", "location": "Lagos", "address": "5 Mobolaji Bank Anthony Way, Maryland, Lagos"},
  {"id": 92, "name": "Nizamiye Hospital", "location": "Abuja", "address": "Cadastral Zone B04, Abuja"},
  {"id": 93, "name": "Primus Hospital", "location": "Abuja", "address": "Karimu Kotun Close, Abuja"},
  {"id": 94, "name": "Zenith Medical and Kidney Centre", "location": "Abuja", "address": "Plot 1075, Abuja"},
  {"id": 95, "name": "St. Edwards Hospital", "location": "Lagos", "address": "55 Bourdillon Road, Ikoyi, Lagos"},
  {"id": 96, "name": "St. Gregory's Hospital", "location": "Lagos", "address": "10b Olorunlogbon Street, Anthony Village, Lagos"},
  {"id": 97, "name": "Holy Trinity Hospital", "location": "Lagos", "address": "142 Akowonjo Road, Egbeda, Lagos"},
  {"id": 98, "name": "Medicare Specialist Hospital", "location": "Lagos", "address": "14B Ladoke Akintola Street, Ikeja GRA, Lagos"},
  {"id": 99, "name": "South Shore Women's and Children's Hospital", "location": "Lagos", "address": "11 Olabanji Olajide Street, Lekki Phase 1, Lagos"},
  {"id": 100, "name": "Doren Specialist Hospital", "location": "Lagos", "address": "21 Emina Crescent, Off Toyin Street, Ikeja, Lagos"},
  {"id": 101, "name": "Lagoon Hospitals", "location": "Lagos", "address": "Plot 8, Block 79, Providence Street, Lekki Phase 1, Lagos"},
  {"id": 102, "name": "Alimosho General Hospital", "location": "Lagos", "address": "LASU/Isheri Expressway, Igando, Lagos"},
  {"id": 103, "name": "Ajeromi General Hospital", "location": "Lagos", "address": "Baale Street, Ajegunle, Lagos"},
  {"id": 104, "name": "Badagry General Hospital", "location": "Lagos", "address": "Hospital Road, Badagry, Lagos"},
  {"id": 105, "name": "Ibeju-Lekki General Hospital", "location": "Lagos", "address": "Lekki-Epe Expressway, Ibeju-Lekki, Lagos"},
  {"id": 106, "name": "Iganmu General Hospital", "location": "Lagos", "address": "Western Avenue, Iganmu, Lagos"},
  {"id": 107, "name": "Epe General Hospital", "location": "Lagos", "address": "Hospital Road, Epe, Lagos"},
  {"id": 108, "name": "Gbagada General Hospital", "location": "Lagos", "address": "Gbagada Expressway, Gbagada, Lagos"},
  {"id": 109, "name": "Badagry General Hospital", "location": "Lagos", "address": "Hospital Road, Badagry, Lagos"},
  {"id": 110, "name": "Isolo General Hospital", "location": "Lagos", "address": "Isolo Road, Isolo, Lagos"},
  {"id": 111, "name": "Gwagwalada Specialist Hospital", "location": "Abuja", "address": "Gwagwalada - Kuje Road, Gwagwalada, Abuja"},
  {"id": 112, "name": "Asokoro District Hospital", "location": "Abuja", "address": "Kapital Street, Asokoro, Abuja"},
  {"id": 113, "name": "Wuse District Hospital", "location": "Abuja", "address": "Kur Mohammed Avenue, Wuse, Abuja"},
  {"id": 114, "name": "Garki District Hospital", "location": "Abuja", "address": "Sokode Crescent, Garki, Abuja"},
  {"id": 115, "name": "Kubwa General Hospital", "location": "Abuja", "address": "Phase 2 Site 2, Kubwa, Abuja"},
  {"id": 116, "name": "Kuje General Hospital", "location": "Abuja", "address": "Kuje - Gwagwalada Road, Kuje, Abuja"},
  {"id": 117, "name": "Federal Medical Centre, Kuje", "location": "Kuje", "address": "Kuje - Gwagwalada Road, Kuje, Abuja"},
  {"id": 118, "name": "University of Ilorin Teaching Hospital", "location": "Ilorin", "address": "University of Ilorin Campus, Oke Oyi, Ilorin"},
  {"id": 119, "name": "Ado Ekiti Specialist Hospital", "location": "Ado Ekiti", "address": "Ado - Iworoko Road, Ado Ekiti"},
  {"id": 120, "name": "Akure Specialist Hospital", "location": "Akure", "address": "Ondo Road, Akure"},
  {"id": 121, "name": "Abeokuta Specialist Hospital", "location": "Abeokuta", "address": "Oke-Mosan Road, Abeokuta"},
  {"id": 122, "name": "Ife Central Hospital", "location": "Ife", "address": "Ibadan Road, Ife, Osun State"},
  {"id": 123, "name": "Osogbo Specialist Hospital", "location": "Osogbo", "address": "Iwo Road, Osogbo"},
  {"id": 124, "name": "Ijebu-Ode General Hospital", "location": "Ijebu-Ode", "address": "Oke-Eran Road, Ijebu-Ode"},
  {"id": 125, "name": "Sagamu General Hospital", "location": "Sagamu", "address": "Sagamu - Benin Expressway, Sagamu"},
  {"id": 126, "name": "Ikorodu General Hospital", "location": "Ikorodu", "address": "Ikorodu Road, Ikorodu, Lagos"},
  {"id": 127, "name": "General Hospital, Ikeja", "location": "Ikeja", "address": "Obafemi Awolowo Way, Ikeja, Lagos"},
  {"id": 128, "name": "General Hospital, Surulere", "location": "Surulere", "address": "Adeniran Ogunsanya Street, Surulere, Lagos"},
  {"id": 129, "name": "General Hospital, Mushin", "location": "Mushin", "address": "LUTH Road, Mushin, Lagos"},
  {"id": 130, "name": "General Hospital, Apapa", "location": "Apapa", "address": "Lagos - Badagry Expressway, Apapa, Lagos"}
]