export const healthCareList = [
    { "id": 1, "name": "Lagos University Teaching Hospital", "location": "Lagos" },
    { "id": 2, "name": "University College Hospital", "location": "Ibadan" },
    { "id": 3, "name": "National Hospital Abuja", "location": "Abuja" },
    { "id": 4, "name": "Aminu Kano Teaching Hospital", "location": "Kano" },
    { "id": 5, "name": "University of Nigeria Teaching Hospital", "location": "Enugu" },
    { "id": 6, "name": "Ahmadu Bello University Teaching Hospital", "location": "Zaria" },
    { "id": 7, "name": "Federal Medical Centre, Ebute Metta", "location": "Lagos" },
    { "id": 8, "name": "University of Benin Teaching Hospital", "location": "Benin" },
    { "id": 9, "name": "University of Port Harcourt Teaching Hospital", "location": "Port Harcourt" },
    { "id": 10, "name": "Federal Medical Centre, Asaba", "location": "Asaba" },
    { "id": 11, "name": "Lagos State University Teaching Hospital", "location": "Lagos" },
    { "id": 12, "name": "Federal Medical Centre, Umuahia", "location": "Umuahia" },
    { "id": 13, "name": "University of Ilorin Teaching Hospital", "location": "Ilorin" },
    { "id": 14, "name": "Federal Medical Centre, Abeokuta", "location": "Abeokuta" },
    { "id": 15, "name": "Nnamdi Azikiwe University Teaching Hospital", "location": "Nnewi" },
    { "id": 16, "name": "Federal Medical Centre, Owerri", "location": "Owerri" },
    { "id": 17, "name": "Federal Medical Centre, Yola", "location": "Yola" },
    { "id": 18, "name": "Federal Medical Centre, Makurdi", "location": "Makurdi" },
    { "id": 19, "name": "Federal Medical Centre, Birnin Kudu", "location": "Birnin Kudu" },
    { "id": 20, "name": "Lagos State University Teaching Hospital", "location": "Lagos" },
    { "id": 21, "name": "Federal Medical Centre, Bida", "location": "Bida" },
    { "id": 22, "name": "Federal Medical Centre, Lokoja", "location": "Lokoja" },
    { "id": 23, "name": "Niger Delta University Teaching Hospital", "location": "Bayelsa" },
    { "id": 24, "name": "Federal Medical Centre, Jalingo", "location": "Jalingo" },
    { "id": 25, "name": "Federal Medical Centre, Gombe", "location": "Gombe" },
    { "id": 26, "name": "Federal Medical Centre, Gusau", "location": "Gusau" },
    { "id": 27, "name": "Federal Medical Centre, Katsina", "location": "Katsina" },
    { "id": 28, "name": "Federal Medical Centre, Keffi", "location": "Keffi" },
    { "id": 29, "name": "Federal Medical Centre, Lafia", "location": "Lafia" },
    { "id": 30, "name": "Federal Medical Centre, Lokoja", "location": "Lokoja" },
    { "id": 31, "name": "Federal Medical Centre, Owo", "location": "Owo" },
    { "id": 32, "name": "Federal Medical Centre, Owerri", "location": "Owerri" },
    { "id": 33, "name": "Federal Medical Centre, Sokoto", "location": "Sokoto" },
    { "id": 34, "name": "Federal Medical Centre, Umuahia", "location": "Umuahia" },
    { "id": 35, "name": "Federal Medical Centre, Yenagoa", "location": "Yenagoa" },
    { "id": 36, "name": "Federal Medical Centre, Abeokuta", "location": "Abeokuta" },
    { "id": 37, "name": "Federal Medical Centre, Azare", "location": "Azare" },
    { "id": 38, "name": "Federal Medical Centre, Bida", "location": "Bida" },
    { "id": 39, "name": "Federal Medical Centre, Birnin Kudu", "location": "Birnin Kudu" },
    { "id": 40, "name": "Federal Medical Centre, Damaturu", "location": "Damaturu" },
    { "id": 41, "name": "Federal Medical Centre, Ebute Metta", "location": "Lagos" },
    { "id": 42, "name": "Federal Medical Centre, Gombe", "location": "Gombe" },
    { "id": 43, "name": "Federal Medical Centre, Gusau", "location": "Gusau" },
    { "id": 44, "name": "Federal Medical Centre, Ido-Ekiti", "location": "Ido-Ekiti" },
    { "id": 45, "name": "Federal Medical Centre, Jalingo", "location": "Jalingo" },
    { "id": 46, "name": "Federal Medical Centre, Katsina", "location": "Katsina" },
    { "id": 47, "name": "Federal Medical Centre, Keffi", "location": "Keffi" },
    { "id": 48, "name": "Federal Medical Centre, Lokoja", "location": "Lokoja" },
    { "id": 49, "name": "Federal Medical Centre, Owerri", "location": "Owerri" },
    { "id": 50, "name": "Federal Medical Centre, Sokoto", "location": "Sokoto" },
    { "id": 51, "name": "General Hospital, Minna", "location": "Minna" },
    { "id": 52, "name": "General Hospital, Zaria", "location": "Zaria" },
    { "id": 53, "name": "Isolo General Hospital", "location": "Lagos" },
    { "id": 54, "name": "Gbagada General Hospital", "location": "Lagos" },
    { "id": 55, "name": "Ikorodu General Hospital", "location": "Lagos" },
    { "id": 56, "name": "Gwagwalada Specialist Hospital", "location": "Abuja" },
    { "id": 57, "name": "National Orthopaedic Hospital, Enugu", "location": "Enugu" },
    { "id": 58, "name": "Federal Medical Centre, Abakaliki", "location": "Abakaliki" },
    { "id": 59, "name": "Adeoyo Maternity Hospital", "location": "Ibadan" },
    { "id": 60, "name": "Eko Hospital", "location": "Lagos" },
    { "id": 61, "name": "Reddington Hospital", "location": "Lagos" },
    { "id": 62, "name": "St. Nicholas Hospital", "location": "Lagos" },
    { "id": 63, "name": "First Consultant Hospital", "location": "Lagos" },
    { "id": 64, "name": "Nizamiye Hospital", "location": "Abuja" },
    { "id": 65, "name": "Primus Hospital", "location": "Abuja" },
    { "id": 66, "name": "Zenith Medical and Kidney Centre", "location": "Abuja" },
    { "id": 67, "name": "St. Edwards Hospital", "location": "Lagos" },
    { "id": 68, "name": "St. Gregory's Hospital", "location": "Lagos" },
    { "id": 69, "name": "Holy Trinity Hospital", "location": "Lagos" },
    { "id": 70, "name": "Medicare Specialist Hospital", "location": "Lagos" },
    { "id": 71, "name": "South Shore Women's and Children's Hospital", "location": "Lagos" },
    { "id": 72, "name": "Doren Specialist Hospital", "location": "Lagos" },
    { "id": 73, "name": "Lagoon Hospitals", "location": "Lagos" },
    { "id": 74, "name": "Eko Hospital", "location": "Lagos" },
    { "id": 75, "name": "Reddington Hospital", "location": "Lagos" },
    { "id": 76, "name": "St. Nicholas Hospital", "location": "Lagos" },
    { "id": 77, "name": "First Consultant Hospital", "location": "Lagos" },
    { "id": 78, "name": "Nizamiye Hospital", "location": "Abuja" },
    { "id": 79, "name": "Primus Hospital", "location": "Abuja" },
    { "id": 80, "name": "Zenith Medical and Kidney Centre", "location": "Abuja" },
    { "id": 81, "name": "St. Edwards Hospital", "location": "Lagos" },
    { "id": 82, "name": "St. Gregory's Hospital", "location": "Lagos" },
    { "id": 83, "name": "Holy Trinity Hospital", "location": "Lagos" },
    { "id": 84, "name": "Medicare Specialist Hospital", "location": "Lagos" },
    { "id": 85, "name": "South Shore Women's and Children's Hospital", "location": "Lagos" },
    { "id": 86, "name": "Doren Specialist Hospital", "location": "Lagos" },
    { "id": 87, "name": "Lagoon Hospitals", "location": "Lagos" },
    { "id": 88, "name": "Eko Hospital", "location": "Lagos" },
    { "id": 89, "name": "Reddington Hospital", "location": "Lagos" },
    { "id": 90, "name": "St. Nicholas Hospital", "location": "Lagos" },
    { "id": 91, "name": "First Consultant Hospital", "location": "Lagos" },
    { "id": 92, "name": "Nizamiye Hospital", "location": "Abuja" },
    { "id": 93, "name": "Primus Hospital", "location": "Abuja" },
    { "id": 94, "name": "Zenith Medical and Kidney Centre", "location": "Abuja" },
    { "id": 95, "name": "St. Edwards Hospital", "location": "Lagos" },
    { "id": 96, "name": "St. Gregory's Hospital", "location": "Lagos" },
    { "id": 97, "name": "Holy Trinity Hospital", "location": "Lagos" },
    { "id": 98, "name": "Medicare Specialist Hospital", "location": "Lagos" },
    { "id": 99, "name": "South Shore Women's and Children's Hospital", "location": "Lagos" },
    { "id": 100, "name": "Doren Specialist Hospital", "location": "Lagos" }
  ]